COMMODITIES = {
    "ZC": {"name": "Corn", "stooq": "zc.f", "yahoo": "ZC=F", "category": "grains", "unit": "cents/bu"},
    "ZS": {"name": "Soybeans", "stooq": "zs.f", "yahoo": "ZS=F", "category": "grains", "unit": "cents/bu"},
    "ZW": {"name": "Wheat CBOT", "stooq": "zw.f", "yahoo": "ZW=F", "category": "grains", "unit": "cents/bu"},
    "KE": {"name": "Wheat KC", "stooq": "ke.f", "yahoo": "KE=F", "category": "grains", "unit": "cents/bu"},
    "ZM": {"name": "Soybean Meal", "stooq": "zm.f", "yahoo": "ZM=F", "category": "grains", "unit": "USD/st"},
    "ZL": {"name": "Soybean Oil", "stooq": "zl.f", "yahoo": "ZL=F", "category": "grains", "unit": "cents/lb"},
    "SB": {"name": "Sugar", "stooq": "sb.f", "yahoo": "SB=F", "category": "softs", "unit": "cents/lb"},
    "KC": {"name": "Coffee", "stooq": "kc.f", "yahoo": "KC=F", "category": "softs", "unit": "cents/lb"},
    "CT": {"name": "Cotton", "stooq": "ct.f", "yahoo": "CT=F", "category": "softs", "unit": "cents/lb"},
    "CC": {"name": "Cocoa", "stooq": "cc.f", "yahoo": "CC=F", "category": "softs", "unit": "USD/mt"},
    "OJ": {"name": "Orange Juice", "stooq": "oj.f", "yahoo": "OJ=F", "category": "softs", "unit": "cents/lb"},
    "LE": {"name": "Live Cattle", "stooq": "le.f", "yahoo": "LE=F", "category": "livestock", "unit": "cents/lb"},
    "GF": {"name": "Feeder Cattle", "stooq": "gf.f", "yahoo": "GF=F", "category": "livestock", "unit": "cents/lb"},
    "HE": {"name": "Lean Hogs", "stooq": "he.f", "yahoo": "HE=F", "category": "livestock", "unit": "cents/lb"},
    "CL": {"name": "Crude Oil", "stooq": "cl.f", "yahoo": "CL=F", "category": "energy", "unit": "USD/bbl"},
    "NG": {"name": "Natural Gas", "stooq": "ng.f", "yahoo": "NG=F", "category": "energy", "unit": "USD/MMBtu"},
    "GC": {"name": "Gold", "stooq": "gc.f", "yahoo": "GC=F", "category": "metals", "unit": "USD/oz"},
    "SI": {"name": "Silver", "stooq": "si.f", "yahoo": "SI=F", "category": "metals", "unit": "USD/oz"},
    "DX": {"name": "Dollar Index", "stooq": "dx.f", "yahoo": "DX-Y.NYB", "category": "macro", "unit": "index"},
}
